image: docker
services:
  - docker:dind

stages:
  - build
  - test
  - release

test:
  stage: test
  script:
    - apk add --no-cache make
    - make test

build-release:
  stage: release
  script:
    - echo $CI_JOB_ID # Writing GE_JOB_ID variable to environment file, will need the value in the next stage.
    - echo GE_JOB_ID=$CI_JOB_ID >> build_executables.env
    - apk add --no-cache docker-compose make
    - make build
  artifacts:
    untracked: false
    expire_in: "never"
    paths:
      - "build/windows-amd64-tictacgoe.exe"
      - "build/linux-amd64-tictacgoe"
    reports:
      # To ensure we've access to this file in the next stage
      dotenv: build_executables.env
  needs:
    - job: test
  when: manual

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
  needs:
    - job: build-release
      artifacts: true
  release:
    name: 'Release Executables $CI_COMMIT_TITLE'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TITLE'
    assets:
      links:
        - name: 'Linux executable'
          url: 'https://gitlab.com/Soockee/tictacgoe/-/jobs/${GE_JOB_ID}/artifacts/raw/build/linux-amd64-tictacgoe'
        - name: 'Windows executable'
          url: 'https://gitlab.com/Soockee/tictacgoe/-/jobs/${GE_JOB_ID}/artifacts/raw/build/windows-amd64-tictacgoe.exe'