on:
    release:
        types: [created]
  
permissions:
    contents: write
    packages: write

jobs:
    releases-matrix:
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-tictacgoe')
        name: Release Go Binary
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: ["js"]
                goarch: ["wasm"]    
        steps:
        - uses: actions/checkout@v4
        - uses: wangyoucao577/go-release-action@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            goversion: "https://go.dev/dl/go1.22.1.linux-amd64.tar.gz"
            project_path: "./tictacgoe/cmd/tictacgoe"
            binary_name: "tictacgoe.wasm"